name: pylint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: fetch dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: analyse
      run: |
        pylint `ls -R|grep .py$|xargs`
